name: issue-monitor

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: Github token
        required: true

permissions:
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: monitor issues
        permissions:
          issues: write
        run: |
          gh issue create --title "welcome" --body "very first issue" --repo $GITHUB_REPOSITORY
          gh search issues --repo $GITHUB_REPOSITORY --state open
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
