name: issue-monitor

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: Github token
        required: true

permissions:
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: monitor issues
        run: |
          echo $$GITHUB_REPOSITORY
          gh search issues --repo $GITHUB_REPOSITORY --state open
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
