name: issue-monitor

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: Github token
        required: true

permissions:
  actions: read
  checks: read
  contents: read
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: monitor issues
        run: |
          gh issue create --title "test" --body "very first issue" --repo $GITHUB_REPOSITORY
          if [ -z "$(gh search issues --repo $GITHUB_REPOSITORY) ]; then
            gh issue create --title "welcome" --body "very first issue" --repo $GITHUB_REPOSITORY
          fi
          gh search issues --repo $GITHUB_REPOSITORY --state open
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
