name: issue-monitor

on:
  workflow_call

permissions:
  contents: read
  packages: read

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: monitor issues
        run: |
          env
